export {
  createLocalFixtureProfileProvider,
  type LocalFixtureProfileProvider,
  type LocalFixtureProfileProviderOptions,
} from "./local-fixture-profile-provider.ts";
export {
  localRepositoryConfigHardLimits,
  localRepositoryConfigVersion,
  nodeCanonicalDirectoryPort,
  resolveAuthorizedRepositoryConfig,
  type AuthorizedRepositoryConfigErrorCategory,
  type CanonicalDirectoryPort,
  type LocalPathPlatform,
  type ResolvedAuthorizedRepositoryConfig,
  type ResolvedAuthorizedRoot,
  type ResolvedCollectionLimits,
  type ResolvedSelectedRepository,
  type ResolveAuthorizedRepositoryConfigResult,
} from "./authorized-repository-config.ts";
export {
  collectFilesystemMetadata,
  filesystemMetadataSnapshotVersion,
  nodeFilesystemMetadataPort,
  type BoundedFileRead,
  type CollectFilesystemMetadataResult,
  type DocumentMetadataFile,
  type FilesystemMetadataErrorCategory,
  type FilesystemMetadataFile,
  type FilesystemMetadataPort,
  type FilesystemMetadataSnapshot,
  type InspectedFilesystemPath,
  type InspectedPathKind,
  type ManifestMetadataFile,
  type PackageJsonMetadata,
  type RepositoryFilesystemMetadata,
  type SourceMetadataFile,
} from "./filesystem-metadata-collector.ts";
export {
  nodeBoundedGitCommandPort,
  type BoundedGitCommandFailureReason,
  type BoundedGitCommandPort,
  type BoundedGitCommandRequest,
  type BoundedGitCommandResult,
  type GitObjectFormat,
} from "./bounded-git-command.ts";
export {
  collectGitMetadata,
  gitMetadataHardLimits,
  gitMetadataSnapshotVersion,
  type CollectGitMetadataResult,
  type GitCommitMetadata,
  type GitMetadataErrorCategory,
  type GitMetadataSnapshot,
  type RepositoryGitMetadata,
} from "./git-metadata-collector.ts";
export {
  developerIdentityConfigHardLimits,
  developerIdentityConfigVersion,
  resolveDeveloperIdentityConfig,
  type DeveloperIdentityConfigErrorCategory,
  type GitCommitAnnotationKind,
  type GitIdentityRole,
  type ResolvedDeveloperIdentityConfig,
  type ResolvedGitCommitAnnotation,
  type ResolvedGitIdentity,
  type ResolveDeveloperIdentityConfigResult,
} from "./developer-identity-config.ts";
export {
  assessGitAuthorship,
  gitAuthorshipAssessmentVersion,
  type AssessGitAuthorshipResult,
  type GitAttributionState,
  type GitAuthorshipAssessmentErrorCategory,
  type GitAuthorshipAssessmentSnapshot,
  type GitAuthorshipLimitation,
  type GitCommitAuthorshipAssessment,
  type GitHistoryShape,
  type RepositoryGitAuthorshipAssessment,
} from "./git-authorship-assessment.ts";
export {
  evidenceSourceRiskConfigHardLimits,
  evidenceSourceRiskConfigVersion,
  resolveEvidenceSourceRiskConfig,
  type ConfigurablePathRisk,
  type ConfigurableRepositoryRisk,
  type EvidenceSourceRiskConfigErrorCategory,
  type EvidenceSourceRiskFlag,
  type ResolvedEvidenceSourceRiskConfig,
  type ResolvedPathRiskAnnotation,
  type ResolvedRepositoryRiskAnnotation,
  type ResolveEvidenceSourceRiskConfigResult,
} from "./evidence-source-risk-config.ts";
export {
  classifyEvidenceSourceRisk,
  evidenceSourceRiskSnapshotVersion,
  type ClassifyEvidenceSourceRiskResult,
  type EvidenceSourceLimitation,
  type EvidenceSourceRiskErrorCategory,
  type EvidenceSourceRiskRecord,
  type EvidenceSourceRiskSnapshot,
  type RepositoryEvidenceSourceRisk,
} from "./evidence-source-risk-classifier.ts";
export {
  communityProfileStoreMaximumBytes,
  communityProfileStoreSchemaVersion,
  legacyCommunityProfileStoreSchemaVersion,
  migrateCommunityProfileStore,
  parseCommunityProfileStore,
  serializeCommunityProfileStore,
  type CommunityProfileStore,
  type CommunityProfileStoreFormatErrorCategory,
  type LegacyCommunityProfileStore,
  type MigrateCommunityProfileStoreResult,
  type ParseCommunityProfileStoreResult,
  type ParsedCommunityProfileStore,
} from "./community-profile-store-format.ts";
export {
  localProfileStoreConfigMaximumBytes,
  localProfileStoreConfigVersion,
  resolveLocalProfileStoreConfig,
  type LocalProfileStoreConfigErrorCategory,
  type ResolvedLocalProfileStoreConfig,
  type ResolveLocalProfileStoreConfigResult,
} from "./local-profile-store-config.ts";
export {
  loadLocalProfileStore,
  localProfileStoreHardLimits,
  nodeLocalProfileStorePort,
  writeLocalProfileStore,
  type LoadedLocalProfileStore,
  type LoadLocalProfileStoreResult,
  type LocalProfileStoreDirectoryInspection,
  type LocalProfileStoreErrorCategory,
  type LocalProfileStoreFilePort,
  type WriteLocalProfileStoreResult,
} from "./local-profile-store.ts";
