export {
  createLocalFixtureProfileProvider,
  type LocalFixtureProfileProvider,
  type LocalFixtureProfileProviderOptions,
} from "./local-fixture-profile-provider.ts";
export {
  localRepositoryConfigHardLimits,
  localRepositoryConfigVersion,
  nodeCanonicalDirectoryPort,
  resolveAuthorizedRepositoryConfig,
  type AuthorizedRepositoryConfigErrorCategory,
  type CanonicalDirectoryPort,
  type LocalPathPlatform,
  type ResolvedAuthorizedRepositoryConfig,
  type ResolvedAuthorizedRoot,
  type ResolvedCollectionLimits,
  type ResolvedSelectedRepository,
  type ResolveAuthorizedRepositoryConfigResult,
} from "./authorized-repository-config.ts";
export {
  collectFilesystemMetadata,
  filesystemMetadataSnapshotVersion,
  nodeFilesystemMetadataPort,
  type BoundedFileRead,
  type CollectFilesystemMetadataResult,
  type DocumentMetadataFile,
  type FilesystemMetadataErrorCategory,
  type FilesystemMetadataFile,
  type FilesystemMetadataPort,
  type FilesystemMetadataSnapshot,
  type InspectedFilesystemPath,
  type InspectedPathKind,
  type ManifestMetadataFile,
  type PackageJsonMetadata,
  type RepositoryFilesystemMetadata,
  type SourceMetadataFile,
} from "./filesystem-metadata-collector.ts";
export {
  nodeBoundedGitCommandPort,
  type BoundedGitCommandFailureReason,
  type BoundedGitCommandPort,
  type BoundedGitCommandRequest,
  type BoundedGitCommandResult,
  type GitObjectFormat,
} from "./bounded-git-command.ts";
export {
  collectGitMetadata,
  gitMetadataHardLimits,
  gitMetadataSnapshotVersion,
  type CollectGitMetadataResult,
  type GitCommitMetadata,
  type GitMetadataErrorCategory,
  type GitMetadataSnapshot,
  type RepositoryGitMetadata,
} from "./git-metadata-collector.ts";
export {
  developerIdentityConfigHardLimits,
  developerIdentityConfigVersion,
  resolveDeveloperIdentityConfig,
  type DeveloperIdentityConfigErrorCategory,
  type GitCommitAnnotationKind,
  type GitIdentityRole,
  type ResolvedDeveloperIdentityConfig,
  type ResolvedGitCommitAnnotation,
  type ResolvedGitIdentity,
  type ResolveDeveloperIdentityConfigResult,
} from "./developer-identity-config.ts";
export {
  assessGitAuthorship,
  gitAuthorshipAssessmentVersion,
  type AssessGitAuthorshipResult,
  type GitAttributionState,
  type GitAuthorshipAssessmentErrorCategory,
  type GitAuthorshipAssessmentSnapshot,
  type GitAuthorshipLimitation,
  type GitCommitAuthorshipAssessment,
  type GitHistoryShape,
  type RepositoryGitAuthorshipAssessment,
} from "./git-authorship-assessment.ts";
